# Generated by Django 6.0.1 on 2026-03-27 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings2', '0004_alter_buildings_data_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='data_creation',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2026, 3, 27, 16, 17, 4, 669893, tzinfo=datetime.timezone.utc)),
        ),
    ]
