# Generated by Django 6.0.1 on 2026-04-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings2', '0005_alter_buildings_data_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='data_creation',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2026, 4, 24, 14, 35, 40, 53232, tzinfo=datetime.timezone.utc)),
        ),
    ]
