# Generated by Django 6.0.1 on 2026-03-27 16:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('diametro', models.FloatField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=25830)),
            ],
            options={
                'db_table': 'arboles',
            },
        ),
        migrations.CreateModel(
            name='Camino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=25830)),
            ],
            options={
                'db_table': 'caminos',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('perimetro', models.FloatField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25830)),
            ],
            options={
                'db_table': 'zonas',
            },
        ),
    ]
